version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/SimpleDB/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
- package-ecosystem: nuget
  directory: "/src/Chirp.CLI/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
