name: .NET Publish and Release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PROJECT_FILE: "src/Chirp.Web/Chirp.Web.csproj"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish for Windows
        shell: bash
        run: |
          #Defining variables
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-win-x64"
          echo Git tag: $tag
          echo Release name: $release_name
          
          #Build program
          dotnet publish "$PROJECT_FILE" --framework net7.0 --runtime win-x64 -p:PublishSingleFile=true --no-self-contained --configuration Release --verbosity normal --output "$release_name"

          #Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          echo Files in directory -----
          dir

          #Delete output directory
          rm -r "$release_name"
          echo Files in directory -----
          dir
      - name: Publish for Linux
        shell: bash
        run: |
          #Defining variables
          tag=$(git describe --tags --abbrev=0)
          release_name=Chirp-$tag-linux-x64
          echo Git tag: $tag
          echo Release name: $release_name

          #Build program
          dotnet publish "$PROJECT_FILE" --framework net7.0 --runtime linux-x64 -p:PublishSingleFile=true --no-self-contained --configuration Release --verbosity normal --output "$release_name"

          #Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          echo Files in directory -----
          dir

          #Delete output directory
          rm -r "$release_name"
          echo Files in directory -----
          dir
      - name: Publish for macOS
        shell: bash
        run: |
          #Defining variables
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-osx-x64"
          echo Git tag: $tag
          echo Release name: $release_name

          #Build program
          dotnet publish "$PROJECT_FILE" --framework net7.0 --runtime osx-x64 -p:PublishSingleFile=true --no-self-contained --configuration Release --verbosity normal --output "$release_name"

          #Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          echo Files in directory -----
          dir

          #Delete output directory
          rm -r "$release_name"
          echo Files in directory -----
          dir
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Chirp-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
