name: .NET Publish and Release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish for Windows
        run: dotnet publish src/Chirp.CLI/Chirp.csproj --no-self-contained --framework net7.0 --runtime win-x64 --configuration Release --verbosity normal --output Chirp-v0.0.0-win-x64
      - name: Zip
        run: tar czvf "Chirp-v0.0.0-win-x64.zip" "./Chirp-v0.0.0-win-x64"
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with: 
          files: "Chirp-v0.0.0-win-x64.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
